# Generated by Django 4.2.4 on 2023-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image_URL',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
