# Generated by Django 4.2.4 on 2023-08-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image_URL',
        ),
    ]
